version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "finance"
      MYSQL_PASSWORD: "root"
    networks:
      - net
    restart: "always"

  redis:
    image: "redis"
    command:
      - "redis-server"
      - "--databases 256"
    networks:
      - net
    volumes:
      - redis-data:/data
    restart: "always"

  finance:
    container_name: finance
    image: finance
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    tty: true
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    depends_on:
      - mariadb
      - redis
    environment:
      APP_ENV: dev
      SCAN_CACHEABLE: false
      DB_DRIVER: "mysql"
      DB_HOST: "mariadb"
      DB_PORT: 3306
      DB_DATABASE: "finance"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
      DB_CHARSET: "utf8mb4"
      DB_COLLATION: "utf8mb4_unicode_ci"
      DB_PREFIX: ""
      REDIS_HOST: "redis"
    networks:
      - net
    restart: "always"
    deploy:
      replicas: 1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: "root"
    ports:
      - "8080:80"
    networks:
      - net
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=your_elastic_password  # Senha do usuário 'elastic'
      - xpack.security.enabled=true                # Habilitar segurança
    ports:
      - "9200:9200"
    networks:
      - net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic            # Usuário para autenticação
      - ELASTICSEARCH_PASSWORD=your_elastic_password # Senha do usuário 'elastic'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - net
    restart: always


  k6:
    image: loadimpact/k6:0.42.0
    container_name: k6
    volumes:
      - ./scripts:/scripts
      - ./results:/results
    networks:
      - net

networks:
  net:

volumes:
  mariadb-data:
  redis-data:
