version: '3'

services:
  mysql:
    image: "mysql/mysql-server:5.7"
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "hyperf"
    networks:
      - net
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.github/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: "always"

  redis:
    image: "redis"
    command:
      - "redis-server"
      - "--databases 256"
    networks:
      - net
    volumes:
      - redis-data:/data
    restart: "always"

  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: dev
      SCAN_CACHEABLE: false
      DB_DRIVER: "mysql"
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB_DATABASE: "hyperf"
      DB_USERNAME: "root"
      DB_PASSWORD: ""
      DB_CHARSET: "utf8mb4"
      DB_COLLATION: "utf8mb4_unicode_ci"
      DB_PREFIX: ""
      REDIS_HOST: "redis"
    networks:
      - net
    restart: "always"
    deploy:
      replicas: 1
networks:
  net:

volumes:
  mysql-data:
  redis-data: