#!/bin/bash

case "$1" in
  start)
    echo "Iniciando os serviços do Docker Compose..."
    docker compose up -d --build
    ;;
  stop)
    echo "Parando os containers..."
    docker compose down
    ;;
  restart)
      echo "Parando os containers..."
      docker compose down
      docker compose up -d
      ;;
  test)
      echo "Executando test no serviço finance..."
      docker compose exec finance composer run-script test
      ;;
  coverage)
      echo "Executando cobertura no serviço finance..."
      docker compose exec finance composer run-script coverage
      ;;
  bash)
      echo "Executando cobertura no serviço finance..."
      docker exec -it finance bash
      ;;
  logs)
    echo "Executando cobertura no serviço finance..."
    docker-compose logs finance -f
    ;;
  *)
    echo "Comandos disponíveis:"
    echo "  start      - Inicia os serviços do Docker Compose"
    echo "  test       - Executa o comando 'test' no serviço finance"
    echo "  coverage   - Executa o comando 'coverage' no serviço finance"
    echo "  stop       - Para e remove os containers"
    ;;
esac
